#Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

#Permission is hereby granted, free of charge, to any person obtaining a copy of this
#software and associated documentation files (the "Software"), to deal in the Software
#without restriction, including without limitation the rights to use, copy, modify,
#merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
#permit persons to whom the Software is furnished to do so.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Defense in Depth using AWS WAF Managed Rules
# Using only AWS Managed Rules for the Application Layer on Application Load Balancers
# https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Defence in depth with AWS WAF Managed Rules.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Public Layer AWS WAF WebACL Name"
        Parameters:
          - ApplicationWebACLNameParam
      -
        Label:
          default: "Public Layer AWS Managed Rule Controls"
        Parameters:
          - AMRWordPressRuleSetExcludedRules
          - AMRPHPRuleSetExcludedRules
          - AMRUnixRuleSetExcludedRules
          - AMRLinuxRuleSetExcludedRules
          - AMRSQLiRuleSetExcludedRules
    ParameterLabels:
      ApplicationWebACLNameParam:
        default: "Web ACL Name" 
Parameters:
  ApplicationWebACLNameParam:
    Description: "AWS WAF WebACL name that would be accosiated to an Application Load Balancer"
    Type: String
    Default: Public-Application-Layer-WebACL
  AMRWordPressRuleSetExcludedRules:
    Description: "By default all rules are set to count mode during an evaluation period. If you want rules to be fully enforced at deployment remove selected or all default inputs."
    Type: CommaDelimitedList
    Default: WordPressExploitablePaths_URIPATH
  AMRPHPRuleSetExcludedRules:
    Description: "By default all rules are set to count mode during an evaluation period. If you want rules to be fully enforced at deployment remove selected or all default inputs."
    Type: CommaDelimitedList
    Default: PHPHighRiskMethodsVariables_QUERYARGUMENTS, PHPHighRiskMethodsVariables_BODY
  AMRUnixRuleSetExcludedRules:
    Description: "By default all rules are set to count mode during an evaluation period. If you want rules to be fully enforced at deployment remove selected or all default inputs."
    Type: CommaDelimitedList
    Default: UNIXShellCommandsVariables_QUERYARGUMENTS, UNIXShellCommandsVariables_BODY
  AMRLinuxRuleSetExcludedRules:
    Description: "By default all rules are set to count mode during an evaluation period. If you want rules to be fully enforced at deployment remove selected or all default inputs."
    Type: CommaDelimitedList
    Default: LFI_URIPATH, LFI_QUERYARGUMENTS, LFI_BODY
  AMRSQLiRuleSetExcludedRules:
    Description: "By default all rules are set to count mode during an evaluation period. If you want rules to be fully enforced at deployment remove selected or all default inputs."
    Type: CommaDelimitedList
    Default: SQLiExtendedPatterns_QUERYARGUMENTS, SQLi_QUERYARGUMENTS, SQLi_BODY, SQLi_COOKIE, SQLi_URIPATH
Resources:
  PublicApplicationLayerWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref ApplicationWebACLNameParam
      Scope: REGIONAL
      Description: Public Application Network Web ACL using AWS Managed Rules.
      DefaultAction: 
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Join
            - ""
            - - !Ref ApplicationWebACLNameParam
              - "Metric"
      Tags:
        - Key: Layer
          Value: Application
      Rules: 
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 0
          OverrideAction: 
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRSQLi
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
              ExcludedRules: !Ref AMRSQLiRuleSetExcludedRules
        - Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRLinux
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet 
              ExcludedRules: !Ref AMRLinuxRuleSetExcludedRules
        - Name: AWS-AWSManagedRulesUnixRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRUnix
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet
              ExcludedRules: !Ref AMRUnixRuleSetExcludedRules
        - Name: AWS-AWSManagedRulesPHPRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRPHP
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesPHPRuleSet 
              ExcludedRules: !Ref AMRPHPRuleSetExcludedRules
        - Name: AWS-AWSManagedRulesWordPressRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRWordPress
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesWordPressRuleSet
              ExcludedRules: !Ref AMRWordPressRuleSetExcludedRules